using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace RecognizedAirPicture
{
    public class RecognizedAircraft
    {
        public string AircraftId { get; set; }
        public string Callsign { get; set; }

        public Position? NextEstimatedPosition { get; set; }

        public List<Position> Positions { get; set; } = new List<Position>();

        public int Altitude { get; set; } = 0;

        public int GroundSpeed { get; set; } = 0;
        public string? Track { get; set; }

        // Generated by the plane and received via message
        public DateTime LastMessageGenerated { get; set; }
        // Taken from the running instance as distributed time is hardly synchronized
        public DateTime LastMessage {  get; set; }

        public bool HasChanged { get; set; }

        public readonly object PlaneLock = new object();

        // When a plane enters the area for the first time
        public RecognizedAircraft(SBSMessageHelper sbsMessage) 
        {
            AircraftId = sbsMessage.FieldHexIdent;
            Callsign = sbsMessage.FieldCallsign;

            LastMessageGenerated = sbsMessage.FieldDateMessageGenerated.ToDateTime(sbsMessage.FieldTimeMessageGenerated).ToUniversalTime();
            LastMessage = DateTime.UtcNow;
            HasChanged = true;


            switch (sbsMessage.FieldTransmissionType)
            {
                case SBSMessageHelper.ESAirbornePositionMessage:
                    Positions.Add(new Position
                    {
                        Latitude = sbsMessage.FieldLatitude,
                        Longitude = sbsMessage.FieldLongitude,
                        Generated = LastMessage
                    });
                    break;
                case SBSMessageHelper.ESAirborneVelocityMessage:
                    GroundSpeed = sbsMessage.FieldGroundSpeed;
                    Track = sbsMessage.FieldTrack;
                    break;
                default:
                    break;
            }

        }

        public Position MeanPosition()
        {
            var latSum = 0.0;
            var lonSum = 0.0;
            foreach (var i in Positions)
            {
                latSum += i.Latitude;
                lonSum += i.Longitude;
            }

            if (Positions.Count > 0)
            {
                // calculate mean
                latSum /= Positions.Count;
                lonSum /= Positions.Count;
            }

            return new Position
            {
                Latitude = latSum,
                Longitude = lonSum
            };
        }

        public Position? GetLastPosition()
        {
            return Positions.OrderBy(position => position.Generated).FirstOrDefault();

        }

        public bool IsOutlierMessage(SBSMessageHelper sbsMessage)
        {
            var lastPosition = GetLastPosition();
            if (lastPosition != null)
            {
                var distance = Geolocation.GeoCalculator.GetDistance(lastPosition.Latitude, lastPosition.Longitude,
                    sbsMessage.FieldLatitude, sbsMessage.FieldLongitude);

                return distance > 200;
            }

            return false;
        }

        public void AddNewEstimatePosition()
        {
            var lastPosition = GetLastPosition();

            int track;
            var parseResult = int.TryParse(Track, out track);
            if (!parseResult || lastPosition is null) { return; }

            const double ratioKnotToKmPerSecond = 0.000514;
            // seconds in the future to calculate the next estimate position.
            const double PositionIn = 10;

            var distance = GroundSpeed * ratioKnotToKmPerSecond * PositionIn;
            Positions.Add(CalculateDestinationPoint(lastPosition.Latitude, lastPosition.Longitude, track, distance));
        }

        /// <summary>
        /// http://www.movable-type.co.uk/scripts/latlong.html
        /// Destination point given distance and bearing from start point
        /// </summary>
        /// <param name="aircraft"></param>
        public static Position CalculateDestinationPoint(double latitudeInDegree, double longitudeInDegree, int trackInDegree, double distance)
        {
            const int earthRadius = 6371;

            var latitudeInRadians = latitudeInDegree * Math.PI / 180;
            var longitudeInRadians = longitudeInDegree * Math.PI / 180;
            var trackInRadians = trackInDegree * Math.PI / 180;

            var estimatedLatitude = Math.Asin(Math.Sin(latitudeInRadians) * Math.Cos(distance / earthRadius) +
            Math.Cos(latitudeInRadians) * Math.Sin(distance / earthRadius) * Math.Cos(trackInRadians));

            var estimatedLongitude = longitudeInRadians +
                Math.Atan2(Math.Sin(trackInRadians) * Math.Sin(distance / earthRadius) *
                    Math.Cos(latitudeInRadians), Math.Cos(distance / earthRadius) -
                    Math.Sin(latitudeInRadians) * Math.Sin(estimatedLatitude));

            return new Position
            {
                Latitude = estimatedLatitude * 180 / Math.PI,
                Longitude = estimatedLongitude * 180 / Math.PI,
                IsEstimated = true,
            };
        }


    }
}
