using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using System.Threading.Tasks;


namespace RecognizedAirPicture
{
    public class RecognizedAircraft
    {
        public static readonly int MAX_MEDIAN_VALUES = 10;

        public string TransponderId { get; set; }
        public string Callsign { get; set; }

        public List<Position> Positions { get; set; } = new List<Position>();

        private int _groundSpeed = -1;
        private List<int> _lastSpeeds { get; set; } = new List<int>();
        public int GroundSpeed {
            get => _groundSpeed;
            set
            {
                AddNewValueToFixedSizeCollection(value, _lastSpeeds);
                _groundSpeed = (int)ApplyMedianFilter(_lastSpeeds);
            }
        }

        private int _track = -1;
        private List<int> _lastTracks { get; set; } = new List<int>();
        public int Track 
        {
            get => _track;
            set
            {
                AddNewValueToFixedSizeCollection(value, _lastTracks);
                _track = (int) ApplyMedianFilter(_lastTracks);
            }
        }


        // Generated by the plane and received via message
        public DateTime LastMessageGenerated { get; set; }
        // Taken from the running instance as distributed time is hardly synchronized
        public DateTime LastMessage {  get; set; }

        public bool HasChanged { get; set; }


        // When a plane enters the area for the first time
        public RecognizedAircraft(SBSMessageHelper sbsMessage) 
        {
            TransponderId = sbsMessage.FieldHexIdent;
            Callsign = sbsMessage.FieldCallsign;

            LastMessageGenerated = sbsMessage.FieldDateMessageGenerated
                .ToDateTime(sbsMessage.FieldTimeMessageGenerated).ToUniversalTime();
            LastMessage = DateTime.UtcNow;
            HasChanged = true;


            switch (sbsMessage.FieldTransmissionType)
            {
                case SBSMessageHelper.ESAirbornePositionMessage:
                    Positions.Add(new Position
                    {
                        Latitude = sbsMessage.FieldLatitude,
                        Longitude = sbsMessage.FieldLongitude,
                        Generated = LastMessage
                    });
                    break;
                case SBSMessageHelper.ESAirborneVelocityMessage:
                    
                    GroundSpeed = sbsMessage.FieldGroundSpeed;
                    Track = sbsMessage.FieldTrack;
                    break;
                default:
                    break;
            }

        }


        public bool HasValidState()
        {
            return Track != -1 && GroundSpeed != -1 && Positions.Count >= 3 &&
                Callsign != string.Empty && TransponderId != string.Empty;
        }

        public Position? GetLastPosition()
        {
            lock (Positions)
            {
                var lastPosition = Positions.OrderByDescending(position => position.Generated).FirstOrDefault();
                return lastPosition;
            }
            
        }

        public bool IsOutlierPosition(SBSMessageHelper sbsMessage)
        {
            // count the estimates before the last actual message
            var countedEstimates = Positions.OrderByDescending(position => position.Generated)
                .TakeWhile(position => position.IsEstimated)
                .Count();

            var lastPosition = GetLastPosition();
            if (lastPosition == null)
            {
                return false;
            }

            var distance = Geolocation.GeoCalculator.GetDistance(lastPosition.Latitude, lastPosition.Longitude,
                    sbsMessage.FieldLatitude, sbsMessage.FieldLongitude);

            var planeSpeed = GroundSpeed;
            var tolerance = 0.5;
            if (planeSpeed == -1)
            {
                // TODO check if correct km/h or knots
                // In case the actual speed is unknown
                planeSpeed = 800;
            }
            return distance > planeSpeed / 3600 + tolerance + Math.Pow(countedEstimates, 2);
        }

        public static double ApplyMedianFilter(ICollection<int> lastValues) 
        {
            if (lastValues.Count == 0) { return 0; }

            var sortedValues = lastValues.OrderBy(value => value).ToList();

            var isEven = sortedValues.Count % 2 == 0;
            double median = 0;
            if (isEven)
            {
                median = (sortedValues[sortedValues.Count / 2 - 1] + sortedValues[sortedValues.Count / 2]) / 2;
            }
            else
            {
                median = sortedValues[sortedValues.Count / 2];
            }
            return median;
        }

        public static void AddNewValueToFixedSizeCollection<T>(T value, ICollection<T> valueCollection)
        {
            if (valueCollection == null) {  return; }

            var values = (List<T>)valueCollection;

            if (values.Count >= MAX_MEDIAN_VALUES)
            {
                values.RemoveAt(0);
            }

            values.Add(value);
        }

        public void AddNewEstimatePosition()
        {
            var lastPosition = GetLastPosition();

            if (lastPosition == null) { return; }

            const double ratioKnotToKmPerSecond = 0.000514;
            // seconds in the future to calculate the next estimate position.
            const double PositionIn = 10;

            var distance = GroundSpeed * ratioKnotToKmPerSecond * PositionIn;
            Positions.Add(CalculateDestinationPoint(lastPosition.Latitude, lastPosition.Longitude, Track, distance));
        }

        /// <summary>
        /// http://www.movable-type.co.uk/scripts/latlong.html
        /// Destination point given distance and bearing from start point
        /// </summary>
        /// <param name="aircraft"></param>
        public static Position CalculateDestinationPoint(double latitudeInDegree, double longitudeInDegree,
            int trackInDegree, double distance)
        {
            const int earthRadius = 6371;

            var latitudeInRadians = latitudeInDegree * Math.PI / 180;
            var longitudeInRadians = longitudeInDegree * Math.PI / 180;
            var trackInRadians = trackInDegree * Math.PI / 180;

            var estimatedLatitude = Math.Asin(Math.Sin(latitudeInRadians) * Math.Cos(distance / earthRadius) +
            Math.Cos(latitudeInRadians) * Math.Sin(distance / earthRadius) * Math.Cos(trackInRadians));

            var estimatedLongitude = longitudeInRadians +
                Math.Atan2(Math.Sin(trackInRadians) * Math.Sin(distance / earthRadius) *
                    Math.Cos(latitudeInRadians), Math.Cos(distance / earthRadius) -
                    Math.Sin(latitudeInRadians) * Math.Sin(estimatedLatitude));

            return new Position
            {
                Latitude = estimatedLatitude * 180 / Math.PI,
                Longitude = estimatedLongitude * 180 / Math.PI,
                IsEstimated = true,
            };
        }


    }
}
